server:
  port: 8088

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=WifiCar
    username: sa
    password: wanghaozhe@@@1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver